

-- DROP DATABASE IF EXISTS "MIRA_DB";

CREATE DATABASE "MIRA_DB"
    WITH
    OWNER = root
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Database: "MIRA_DB"

CREATE TABLE "USER" (
    "USER_ID" UUID PRIMARY KEY,
    "USER_NAME" VARCHAR(50) NOT NULL UNIQUE,
    "EMAIL" VARCHAR(255) NOT NULL UNIQUE,
    "USER_PROFILE_IMAGE_URL" TEXT,
    "PASSWORD" BYTEA NOT NULL,
    "SALT" VARCHAR(16) NOT NULL UNIQUE,
    "DATECREATED" TIMESTAMP NOT NULL,
    "LAST_LOGIN" TIMESTAMP NOT NULL,
    "LAST_PFP_UPDATE" TIMESTAMP NOT NULL,
    "ISACTIVE" BOOLEAN NOT NULL
);

CREATE TABLE "TodoStatus" (
    "TaskStatusID" INT PRIMARY KEY,
    "TaskStatusName" VARCHAR(20)
);

CREATE TABLE "PROJECTSTATUS" (
    "PROJECT_STATUS_ID" INT PRIMARY KEY,
    "PROJECT_STATUS_NAME" VARCHAR(20)
);

CREATE TABLE "PROJECT" (
    "PROJECT_ID" UUID PRIMARY KEY,
    "PROJECT_NAME" VARCHAR(50) NOT NULL,
    "PROJECT_SCOPE" TEXT NOT NULL,
    "PROJECT_STATUS_ID" INT,
    "USER_ID" UUID NOT NULL,
    CONSTRAINT "FK_USER_PROJECT" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("USER_ID"),
    CONSTRAINT "FK_PROJECT_STATUS_PROJECT" FOREIGN KEY ("PROJECT_STATUS_ID") REFERENCES "PROJECTSTATUS" ("PROJECT_STATUS_ID")
);

CREATE TABLE "NOTE" (
    "NOTE_ID" VARCHAR(101) PRIMARY KEY,
    "NOTE_TITLE" VARCHAR(50) NOT NULL,
    "NOTE_BODY" TEXT NOT NULL,
    "PROJECT_ID" UUID NOT NULL,
    CONSTRAINT "FK_PROJECT_NOTE" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("PROJECT_ID")
);

CREATE TABLE "Todos" (
    "Task_ID" UUID PRIMARY KEY,
    "Task_Name" VARCHAR(255),
    "Task_Description" VARCHAR(255),
    "TaskStatusID" INT,
    "Task_Start" TIMESTAMP,
    "Task_End" TIMESTAMP,
    "PROJECT_ID" UUID,
    CONSTRAINT "FK_TODO_STATUS_TODOS" FOREIGN KEY ("TaskStatusID") REFERENCES "TodoStatus" ("TaskStatusID"),
    CONSTRAINT "FK_PROJECT_TODOS" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("PROJECT_ID")
);

CREATE TABLE "Repository" (
    "Repository_ID" TEXT PRIMARY KEY,
    "Repository_Name" TEXT NOT NULL,
    "Repository_Url" TEXT NOT NULL,
    "PROJECT_ID" UUID NOT NULL,
    CONSTRAINT "FK_PROJECT_REPOSITORY" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("PROJECT_ID")
);

INSERT INTO "TodoStatus" ("TaskStatusID", "TaskStatusName")
VALUES
    (0, 'NOT_STARTED'),
    (1, 'IN_PROGRESS'),
    (2, 'DELAYED'),
    (3, 'CANCELLED'),
    (4, 'COMPLETED');

INSERT INTO "PROJECTSTATUS" ("PROJECT_STATUS_ID", "PROJECT_STATUS_NAME")
VALUES
    (0, 'NOT_STARTED'),
    (1, 'IN_PROGRESS'),
    (2, 'DELAYED'),
    (3, 'CANCELLED'),
    (4, 'COMPLETED');

select * from PROJECTSTATUS