import './globals.css'
import { Inter } from 'next/font/google'
import { Footer } from '@/components/footer/Footer'
import { Navbar } from '@/components/navbar/Navbar'
import { QueryClientProvider, QueryClient } from '@tanstack/react-query'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'mira pm',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const _client = new QueryClient()
  return (

    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={_client}>
          <Navbar />
          {children}
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  )
}
